### PR TITLE
Fixing Download Ubuntu Desktop Url

### PR DESCRIPTION
**Pull request by digital-flowers**

### CODE REVIEW

**Comment by jcupitt** [comment]
OK, merged, thank you!

Did you see build-win64? That's the build script we are using for vips at the moment. 

https://github.com/jcupitt/build-win64

It's containerized, so you can do the entire thing with a single command without disturbing your host system. It also makes a 64-bit Windows binary.

**Comment by digital-flowers** [comment]
Thank you, actually i am building a desktop application using node webkit and i need to run libvips in 32bit machine this is why :)

**Comment by jcupitt** [comment]
Ah, OK. Good luck!

You'll find this repository is a bit out of date, you'll need to check the dependencies and update the modules file.

**Comment by digital-flowers** [comment]
sure, after doing my test i will update the documentation, these days you will have some people need this specially for electron/nwjs and sharp nodejs module :)

**Comment by jcupitt** [comment]
That would be great, thank you very much.

I think sharp on Windows is 64-bit only now. 

I remembered two more things:

* The win64 repository adds extra steps, like generating `.lib` and `.def` files. You may need to backport this code to win32.

* You will find you cannot link an MSVC C++ program to the C++ API defined by libvips due to compiler differences in name mangling and static initialization. You will need to build the libvips C++ layer in MSVC (not difficult).

I think my advice would be to add an option to the win64 build system to generate a 32-bit binary, it would probably be less work. 

Is there a 64-bit electron on Windows? That's another option.

**Comment by digital-flowers** [comment]
i am using nodewebkit and it is already has 64bit but i need to support also windows 32bit versions ,i hope everything is working fine

**Comment by digital-flowers** [comment]
i forked sharp under https://github.com/digital-flowers/sharp-win32 and now I have libvips works perfectly under windows 32bit inside my NodeWebkit desktop application, I really want to thank you for help :)

**Comment by jcupitt** [comment]
Hey great! I'll try to have a look.

**Comment by digital-flowers** [comment]
now i only have a problem with ImageMagick file path unicode and now i am trying to solve, but still not big issue for me

**Pull request merged**
